# Test neighbourhoods for enrichment of a condition

```{r }
# list.files('~/MirjamHoekstra/R')
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
out_dir <- file.path(Sys.getenv('img_dir'), 'fig6')
dir.create(out_dir, showWarnings = F)

mouse_genes <- tar_read(mono_reporters_mouse)$gene
so <- tar_read(filtered_cleaned_so_6743_manual)
if (F) {
  sce <- tar_read(sce_mouse)
} else {
  sce <- tar_read(sce_mouse_var_genes)
}
library(miloR)
library(SingleCellExperiment)
reducedDim(sce)

tM <- tar_read(tM_mouse)
# tar_make(names = sce_mouse_var_genes)
limma_MRs <- tar_read(stringent_limma_MRs_mouse)
sample_annotation <- tar_read(sample_annotation_mouse)
exp5892 <- tar_read(bulk_5892_so)

if (!exists('so') || so@meta.data$exp[1] != '6743') {
  so <- tar_read(filtered_so_6743)
  sg_levs <- c('Mix PBS', 'Ag-GAS + T', 'Mix + T')
  stopifnot(all(so@meta.data$stim_group %in% sg_levs))
  so@meta.data$stim_group <- factor(so@meta.data$stim_group,
    levels = sg_levs)
}

## Remove IFNa
limma_MR_params <- tar_read(limma_MR_params_mouse)
M_cpm <- tar_read(M_cpm_mouse)
tM <- tar_read(tM_mouse)[, -2]
# tM <- tar_read(tM_mouse)
# tM <- tar_read(tM_mouse)[, c(3, 5, 6, 7)]
RC  <- tM >= limma_MR_params$LL
NRC <- tM < limma_MR_params$UL
MRs <- names(which(
  apply(RC[, 1:5], 1, sum) == 1 &
  apply(NRC[, 1:5], 1, sum) >= 4 &
  abs(apply(tM[, 4:5], 1, sum) - tM[, 6]) <= limma_MR_params$SD
))

non_combo_MRs <- names(which(
  apply(RC[, 1:5], 1, sum) == 1 &
  apply(NRC[, 1:5], 1, sum) >= 4
))


f_genes <- rownames(tar_read(f_gene_var_mouse))
gene_sets <- 
  MRs %>%
  # non_combo_MRs %>%
  { tapply(., colnames(tM)[apply(RC[., 1:5], 1, which.max)], list) } %>%
  map(~intersect(.x, f_genes)) %>%
  { setNames(., gsub('.* ng/ml ', '', names(.))) }

gene_sets[['IFNy']] <- mirjam_genes_220516$IFNy_mono
gene_sets[['TNFa']] <- mirjam_genes_220516$TNFa_mono

map(gene_sets, length)
sum(map_int(gene_sets, length))

if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')

```

```{r }
library(miloR)
library(SummarizedExperiment)

print_plot_eval(print(plotNhoodSizeHist(sce)),
  width = 17.4, height = 10,
  filename = file.path(out_dir,
    glue::glue('mouse_Nhood_sizes.pdf')))

sce <- countCells(
  sce,
  meta.data = data.frame(colData(sce)),
  samples = c('condition_i')
  # samples = c('stim_group')
)
# head(nhoodCounts(sce))

design_M <-
  data.frame(colData(sce)) %>%
  # tibble::rownames_to_column('sample_name') %>%
  dplyr::select(
    condition_i, duration, stim_group,
    matches('mouse')
  ) %>%
  dplyr::distinct() %>%
  dplyr::arrange(condition_i) %>%
  set_rownames(NULL) %>%
  # { set_rownames(., .$sample_name) }
  { . }
design_M <- model.matrix(~1 + stim_group, design_M) %>%
  as.data.frame()
colnames(design_M) <- colnames(design_M) %>%
  stringr::str_replace_all(' |\\+|-', '_')

all_NH_test_DA <-
  colnames(design_M)[2:ncol(design_M)] %>%
  auto_name() %>%
  map(function(cn) {
    testNhoods(
      sce,
      model.contrasts = cn,
      # model.contrasts = 'stim_groupAg_GAS___T',
      design = ~ stim_groupMix___T + stim_groupAg_GAS___T,
      design.df = as.data.frame(design_M)
    ) %>%
    dplyr::mutate(Nhood = unlist(nhoodIndex(sce))) %>%
    { set_rownames(., .$Nhood) } %>%
    # dplyr::arrange(desc(logFC)) %>%
    { . }
  })

sce_s <- sce[, colData(sce)$stim_group == 'Mix + T']
sce@nhoods[colData(sce)$stim_group == 'Mix + T', ]

# all_NH_test_DA[[2]]$SpatialFDR <= 0.05
```

```{r, warning=FALSE}
nrow(all_NH_test_DA[[vn]])
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
for (vn in names(all_NH_test_DA)) {
  mcat <- function(...) cat(..., '\n')

  mcat('\nStim group:', vn)
  mcat('\nEnriched')
  idx <- 
    which(with(all_NH_test_DA[[vn]], SpatialFDR <= .05 & logFC > 0))
  mcat(length(idx), 'Nhood(s)')
  mcat(frac_included_cells(sce, 
      allowed_Nhoods = as.character(all_NH_test_DA[[vn]]$Nhood[idx])))
  mcat(frac_included_cells(sce, 
      allowed_cells = which(colData(sce)$stim_group == 'Mix + T'), 
      allowed_Nhoods = as.character(all_NH_test_DA[[vn]]$Nhood[idx])))

  mcat('\nDepleted')
  idx <- 
    which(with(all_NH_test_DA[[vn]], SpatialFDR <= .05 & logFC < 0))
  mcat(length(idx), 'Nhood(s)')
  mcat(frac_included_cells(sce, 
      allowed_Nhoods = as.character(all_NH_test_DA[[vn]]$Nhood[idx])))
  mcat(frac_included_cells(sce, 
      allowed_cells = which(colData(sce)$stim_group == 'Mix + T'), 
      allowed_Nhoods = as.character(all_NH_test_DA[[vn]]$Nhood[idx])))
  mcat(frac_included_cells(sce, 
      allowed_cells = which(colData(sce)$stim_group == 'Mix PBS'), 
      allowed_Nhoods = as.character(all_NH_test_DA[[vn]]$Nhood[idx])))
  mcat(frac_included_cells(sce, 
      allowed_cells = which(colData(sce)$stim_group == 'Ag-GAS + T'), 
      allowed_Nhoods = as.character(all_NH_test_DA[[vn]]$Nhood[idx])))

}

NH_test_DA <- all_NH_test_DA[['stim_groupMix___T']]
# NH_test_DA <-
#   testNhoods(
#     sce,
#     model.contrasts = 'stim_groupMix___T',
#     # model.contrasts = 'stim_groupAg_GAS___T',
#     design = ~ stim_groupMix___T + stim_groupAg_GAS___T,
#     design.df = as.data.frame(design_M)
#   ) %>%
#   dplyr::arrange(desc(logFC))
```

```{r }
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
library(miloR)

rename_mouse_stimgroup <- function(dtf) {
  dtf <- order_stim_group(dtf)
  dtf$stim_group <- forcats::lvls_revalue(
    dtf$stim_group,
    new_levels = c('Control', 'Ag- T-cell', 'Ag+ T-cell')
  )
  return(dtf)
}

p_dat <-
  as.data.frame(cbind(colData(sce), reducedDim(sce, 'UMAP'))) %>%
  order_stim_group() %>%
  order_duration() %>% 
  rename_mouse_stimgroup() %>%
  { . }
if (F) {
  p_dat$UMAP_1
  p_dat$UMAP_2
  p_dat$stim_group
  p_dat$duration
}

p <-
  plot_dim_reduc(
    p_dat,
    coord_regex = 'UMAP_',
    colour_var = 'stim_group',
    use_stim_group_cols = FALSE,
    shape_var = NULL
  ) +
  theme(legend.position = 'bottom') +
  guides(
    color = guide_legend(
      ncol = 1,
      override.aes = list(alpha = 1)
    )
  ) +
  theme()

if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
# p2 <- plotNhoodGraphDA(sce, da_results, layout="umap",alpha=0.05)
p2 <- plotNhoodGraphDA(
  x = sce,
  layout = 'UMAP',
  # milo_res = NH_test_DA[match(unlist(nhoodIndex(sce)),
  #   NH_test_DA$Nhood), ],
  milo_res = all_NH_test_DA[[1]],
  alpha = .05) +
  theme_cyto_inf() +
  theme(plot.title = element_text(hjust = .5)) +
  scale_fill_gradient2(
    name = 'logFC DA', 
    limits = range(all_NH_test_DA[[2]]$logFC)
  ) +
  theme_tabula_rasa +
  ggtitle('Ag- T-cell')

p3 <- plotNhoodGraphDA(
  x = sce,
  layout = 'UMAP',
  # milo_res = NH_test_DA[match(unlist(nhoodIndex(sce)),
  #   NH_test_DA$Nhood), ],
  milo_res = all_NH_test_DA[[2]],
  alpha = .05) +
  theme_cyto_inf() +
  theme_tabula_rasa +
  theme(plot.title = element_text(hjust = .5)) +
  scale_fill_gradient2(
    name = 'logFC DA', 
    limits = range(all_NH_test_DA[[2]]$logFC)
  ) +
  ggtitle('Ag+ T-cell')

print_plot_eval(
  print((p + plot_spacer()) / (p2 + p3 + plot_layout(guides = 'collect'))),
  width = 17.4, height = 20,
  filename = file.path(
    out_dir,
    glue::glue('mouse_Nhood_HL_UMAP.pdf')
  )
)
```


```{r, echo = FALSE options}
gene = 'Ckb'
gene = 'Itga5'
gene = 'Smad7'
gene = 'Gjb3'
colData(sce)[[gene]] <- NA_real_
colData(sce)[[gene]][as.integer(colnames(nhoodExpression(sce)))] <-
  # unname(nhoodExpression(sce)[gene, ])
  unname(min_max_scaling(nhoodExpression(sce)[gene, ]))

colData(sce)[[gene]]

p0 <- plotNhoodGraph(
  x = sce,
  colour_by = gene) +
  theme_cyto_inf() +
  gg_tabula_rasa +
  xlab('') +
  ylab('') +
  guides(size = 'none', edge = 'none') +
  theme(legend.position = 'right', legend.direction = 'vertical')

print_plot_eval(print(p0),
  width = 17.4, height = 10,
  filename = file.path(out_dir,
    glue::glue('{gene}_Nhoods.pdf')))
```


Compare T-cell exposed to non-exposed using Milo
Globally, which genes associate with T-cell exposed cells?

```{r }
# gene_idxs <- which(dge_smp$logCPM_6 >= mean(dge_smp$logCPM_6))

Nhood_expression <- calcNhoodExpression(sce)

M_cpm <- tar_read(M_cpm_mouse)
# meanE <- apply(M_cpm, 1, mean)
# maxE <- apply(M_cpm, 1, max)
# gene_idxs <- which(meanE >= mean(maxE))
# gene_idxs <- which(maxE >= mean(maxE))
# setdiff(names(cors), names(gene_idxs))
# setdiff(names(gene_idxs), names(cors))

cors_fn <- file.path(rds_dir, 'DA_gene_cors_mouse.rds')
cors_fn <- file.path(rds_dir, 'DA_gene_cors_mouse_all_genes.rds')
cors_fn <- file.path(rds_dir, 'DA_gene_cors_mouse_all_genes_var_genes.rds')
if (!file.exists(cors_fn)) {
  cors <-
    rownames(assay(Nhood_expression, 'logcounts')) %>%
    intersect(rownames(M_cpm)) %>%
    auto_name() %>%
    purrr::map(function(g) {
      cor(
        NH_test_DA$logFC,
        assay(Nhood_expression, 'logcounts')[g, NH_test_DA$Nhood],
        method = 'spearman'
      )
    }) %>%
    # setNames(rownames(Nhood_expression)[gene_idxs])
    { . }
  cors <- unlist(cors)
  # quantile(cors, seq(0, 1, .05))
  saveRDS(cors, cors_fn)
} else {
  cors <- readRDS(cors_fn)
}
```

```{r TGFb-MR-HM}
if (interactive())
  source('~/MirjamHoekstra/R/init.R')

plot_DA_panel <- function(
  genes = MRs,
  row_title = 'TGFb mono-responsive genes',
  of = file.path(out_dir,
    glue::glue('TGFb_responsive_genes_HM_ComplexHeatmap_version.pdf'))
  ) {
  do_exclude_unstim_cor = F

  genes <- names(sort(cors[genes]))

  annotation_par <-
    gpar(fontsize = 6, col = 'black',
      lwd = 0, fontfamily = heatmap_font)

  sa <- sample_annotation

  lM <- subset_feats(tar_read(M_cpm_mouse), genes) %>%
    { .[genes, ]}

  idxs <- which(!stringr::str_detect(sa$stim_group, 
      'IFNA|IL-2|A1 B2'))
  sa <- sa[idxs, ]
  lM <- lM[, idxs]
  sa$stim_group <- droplevels(sa$stim_group)

  DE <- GE_vs_stim_dur(
    M = lM,
    min_var = 0,
    cell_width_mm = 1,
    sa = sa[, c('duration', 'stim_group'), drop = F] %>%
      order_stim_group() %>%
      set_rownames(colnames(lM)) %>%
      dplyr::rename(m_sg = stim_group),
    column_clust_method = 'none',
    row_clust_method = 'none',
    plot_name = 'T_cell_associated_genes_mouse',
    show_row_dend = FALSE,
    show_column_dend = FALSE,
    show_row_names = FALSE,
    # N_hl_genes = 21,
    N_hl_genes = NULL,
    height = unit(15, 'cm'),
    show_column_names = FALSE
  )

  Nhood_order <- order(NH_test_DA$logFC)

  stopifnot(all_NH_test_DA[[1]]$Nhood == all_NH_test_DA[[2]]$Nhood)
  stopifnot(NH_test_DA$Nhood == colnames(nhoodExpression(Nhood_expression)))

  TA <- HeatmapAnnotation(
    'Ag_neg' = anno_empty(border = FALSE, height = unit(1.5, "cm")),
    'Ag_pos' = anno_empty(border = FALSE, height = unit(1.5, "cm"))
  )
  RA <- rowAnnotation(
    'cor_ann' = anno_empty(border = FALSE, width = unit(1, 'cm'))
  )

  HM <- gen_HM(
    M = nhoodExpression(Nhood_expression)[genes, Nhood_order] %>%
      apply(1, min_max_scaling) %>%
      t(),
    name = 'Min-max normalized\ngene expression',
    cluster_rows = F,
    show_row_dend = F,
    cluster_columns = F,
    top_annotation = TA,
    right_annotation = RA,
    row_names_side = 'left',
    column_title = 'Neighbourhoods',
    row_title = row_title,
    row_names_gp = gpar(fontsize = 6, col = 'grey20'),
    width = unit(5, "cm")
  )

  print_plot_eval({
    draw(HM + DE, 
      merge_legends = T,
      padding = unit(c(20, 15, 4, 28), 'mm'), 
      heatmap_legend_side = 'bottom')
    titles <- c('Ag- T-cells DA logFC', 'T cell-exposed DA logFC')
    titles <- c('Ag_neg', 'Ag_pos')
    stitles <- c('Ag-\nT-cell\nlogFC DA', 'Ag+\nT cell\nlogFC DA')
    for (i in 1:2) {
      maxFC <- max(abs(unlist(map(all_NH_test_DA, ~.x$logFC))))
      # maxFC <- max(abs(all_NH_test_DA[[i]]$logFC))
      decorate_annotation(
        titles[i], {
          pushViewport(viewport(
              xscale = range(sort(Nhood_order)),
              yscale = maxFC %>% { c(-., .) }
              ))
          grid.lines(x = c(0, max(Nhood_order)), y = c(0.0, 0.0),
            gp = gpar(lty = 2), default.units = 'native')
          grid.yaxis(at = c(0, -round(maxFC)+1, round(maxFC)-1),
            gp = gpar(fontsize = 6, col = 'grey50')
          )
          grid.points(
            x = sort(Nhood_order),
            y = all_NH_test_DA[[i]]$logFC[Nhood_order],
            pch = 19,
            gp = gpar(col =
              ifelse(all_NH_test_DA[[i]]$SpatialFDR[Nhood_order] <= 0.05,
                'indianred2', 'grey50')),
            # size = unit(.5, 'mm')
            size = unit(ifelse(all_NH_test_DA[[i]]$SpatialFDR[Nhood_order] <= 0.05,
                1, .5), 'mm')
          )
          grid.text(stitles[i], 
            # x = 0, y = 0, hjust = 1.5, vjust = 0.0,
            # x = 0, y = 0, vjust = -6,
            x = 0, y = 0, vjust = -2.1,
            gp = gpar(fontsize = 6, col = 'black'),
            rot = 90,
            default.units = 'native'
          )
          popViewport()
        })
    }
    decorate_annotation(
      'cor_ann', {
        pushViewport(viewport(
            xscale = range(cors[genes]) %>%
              { D = diff(.)/10; c(.[1]-D, .[2]+D) },
            yscale = c(length(genes)+.5, .5)
            ))
        grid.lines(
          x = c(0, 0),
          y = c(.5, length(genes)+.5),
          gp = gpar(lty = 2), 
          default.units = "native"
        )
        grid.xaxis(
          # at = c(-.3, .2),
          at = round(range(cors[genes]) * 10) / 10,
          main = TRUE,
          gp = gpar(fontsize = 6, col = 'grey50')
        )
        cols <- gen_col_fun(cors[genes],
          grad_colors = rev(c('skyblue4', 'grey95', 'tomato4'))
        )
        if (T || length(genes) < 50) {
          for (i in 1:length(genes)) {
            grid.lines(
              x = c(0, cors[genes[i]]),
              y = i,
              # gp = gpar(col = "grey50"),
              gp = gpar(col = cols(cors[genes[i]]), 
                width = unit(2, 'mm')),
              default.units = "native"
            )
          }
        }
        grid.points(
          x = cors[genes],
          y = (1:length(genes)),
          pch = 19,
          gp = gpar(col = cols(cors[genes])),
          size = unit(0.5, 'mm'),
          default.units = "native"
        )
        grid.text(
          'Correlation with\nAg+ T-cell condition\nlogFC DA', 
          x = 0, y = 0, hjust = 0.2, vjust = 1.6,
          gp = gpar(fontsize = 6, col = 'black')
        )
        popViewport()
      }
      )},
    width = 20, height = 15,
    filename = of)
}

N = 250
feats <-
  names(sort(abs(cors))) %>%
  { intersect(., rownames(Nhood_expression)) } %>%
  tail(n = N)
plot_DA_panel(
  genes = feats,
  row_title = glue::glue('{N} most strongly correlated genes'),
  of = file.path(out_dir,
    glue::glue('top{N}_DA_panel.pdf'))
)

cors[c('Vim', 'Fn1', 'Cdh2')]
cors[c('Cdh1')]
summary(cors[hallmark_gs[["Interferon gamma response"]]])
summary(cors[hallmark_gs[["TNFa signaling via NFkB"]]])
summary(cors[hallmark_gs[["TGF beta signaling"]]])
summary(cors[hallmark_gs[["Epithelial mesenchymal transition"]]])
summary(cors)


summary(cors[intersect(names(cors), gene_sets[['TGFb']])])
table(sign(cors[intersect(names(cors), gene_sets[['TGFb']])]))

# summary(cors[intersect(names(cors), TGFb_MRs)])
# table(sign(cors[intersect(names(cors), TGFb_MRs)]))

plot_DA_panel(
  genes = gene_sets[['TGFb']],
  row_title = 'TGFb mono-responsive genes',
  of = file.path(out_dir,
    glue::glue('TGFb_responsive_genes_DA_panel.pdf'))
)
```

Pathway analysis on correlated genes

```{r }
devtools::load_all(file.path('~/libs', 'maartenutils'))
library(genesets)

hallmark_gs <-
  filter_gmt(
    pattern = 'HALLMARK',
    # gmt_pattern = 'msigdb',
    gmt_pattern = 'mh.all',
    type = 'symbols'
  )
caplist <- caplist_def %>%
  c('via')
names(hallmark_gs) <- names(hallmark_gs) %>%
  stringr::str_replace('HALLMARK_', '') %>%
  tolower() %>%
  # stringr::str_replace('_', ' ') %>%
  simple_cap(cap_first_word_only = T, caplist = caplist)
names(hallmark_gs)
```

```{r }
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
source('~/MirjamHoekstra/R/gsea.R')

head(sort(cors), n = 30)

p <- gsea_table(
  cors[!is.na(cors)],
  analysis_title = glue::glue('T-cell pressure correlation'),
  min_p = .05,
  max_pathways = 50,
  colwidths = c(3, 3, 0.8, 0, 1.2),
  return_grob = T,
  collapse = FALSE,
  pathways = hallmark_gs
)

print_plot_eval(grid.draw(p),
  width = 17.4, height = 10,
  filename = file.path(out_dir,
    glue::glue('T_cell_pressure_cor_Hallmark.pdf')))
```

# Scatter plots of gene set scores

Do we also see a difference in TGFb/IFNy when stratifying purely on
condition?

```{r }
colnames(M_cpm) <- sample_annotation$sample_name
``` 

```{r }
MAGIC <- readr::read_csv(file.path(data_dir, '6743_Mix_T_MAGIC.csv'))
MAGIC <- MAGIC[, -1] %>%
  { .[, intersect(colnames(.), unlist(gene_sets))] }

gs_p_dat <-
  t(ComputeGeneSetScores(
    M = t(MAGIC), 
    genesets = gene_sets,
    weighting_funcs = all_weighting_funcs[c('unweighted')]
  )) %>%
  as.data.frame() %>%
  { . }

p1 <- ggplot(gs_p_dat, 
  aes_string(y = 'TGFb', x = 'IFNy', colour = 'TNFa')) + 
  geom_point(alpha = .3, size = .5) +
  geom_smooth(method = 'lm') +
  scale_colour_viridis_c()
print_plot_eval(print(p1),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('gs_scores_MAGIC.pdf')))

p1 <- ggplot(gs_p_dat, 
  aes_string(y = 'TGFb', x = 'IFNy', colour = 'TNFa')) + 
  geom_point(alpha = .3, size = .5) +
  geom_smooth(method = 'lm') +
  scale_colour_viridis_c()
print_plot_eval(print(p1),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('gs_scores_MAGIC.pdf')))
```

```{r, warning=FALSE}
geneset_labels <- 
  tibble::enframe(gene_sets, 'gs', 'gene') %>%
  dplyr::mutate(gs = factor(gs, 
      levels = c('TNFa', 'IFNy', 'TGFb'))) %>%
  tidyr::unnest(gene)

plot_corM <- function(corM, fn = file.path(out_dir,
      glue::glue('exp6743_T_cell_MAGIC_corM.pdf'))) {
  HM <- Heatmap(
    corM,
    # column_title = cn,
    name = 'Correlation',
    col <- circlize::colorRamp2(c(-1, 0, 1), 
      c('navyblue', 'white', 'indianred3')),
    left_annotation = rowAnnotation(
      'Gene set' = anno_simple(as.character(geneset_labels$gs[
        match(rownames(corM), geneset_labels$gene)]),
      col = c('TNFa' = 'blue', 'IFNy' = 'red', 'TGFb' = 'yellow'),
      gp = gpar(fontsize = 6))
    ),
    top_annotation = columnAnnotation(
      'Gene set' = anno_simple(as.character(geneset_labels$gs[
        match(rownames(corM), geneset_labels$gene)]),
      col = c('TNFa' = 'blue', 'IFNy' = 'red', 'TGFb' = 'yellow'),
      gp = gpar(fontsize = 6))
    ),
  )
  print_plot_eval(
    draw(HM, merge_legend = TRUE, heatmap_legend_side = 'top'),
    # width = 17.4, 
    width = 17.4, 
    height = 15,
    filename = fn
  )
}

plot_corM(cor(MAGIC, method = 'pearson'), 
  file.path(out_dir, glue::glue('exp6743_T_cell_corM_MAGIC.pdf'))
)

M %>%
  { .[, intersect(colnames(.), unlist(gene_sets))] } %>%
  cor(method = 'pearson') %>%
  plot_corM(file.path(out_dir, glue::glue('exp6743_T_cell_corM.pdf')))
```

```{r }
p_dat <- as.data.frame(MAGIC) %>%
  add_umap()

g1 = 'Galnt1'
g2 = 'Fgl2'
g3 = 'Cx3cl1'
colnames(p_dat)

g1 = 'Tnnt2'
g2 = 'Loxl3'
g2 = 'Bambi'
g2 = 'Batf2'
g2 = 'Clic5'
g2 = 'Cx3cl1'
g3 = 'Col12a1'
g3 = 'Galnt1'
p1 <- ggplot(p_dat, 
  aes_string(x = g1, y = g2, colour = g3)) + 
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p2 <- ggplot(p_dat, 
  aes_string(x = g1, y = g3, colour = g3)) + 
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p3 <- ggplot(p_dat, 
  aes_string(x = 'UMAP1', y = 'UMAP2', colour = g1)) + 
  gg_tabula_rasa +
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p4 <- ggplot(p_dat, 
  aes_string(x = 'UMAP1', y = 'UMAP2', colour = g2)) + 
  gg_tabula_rasa +
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p5 <- ggplot(p_dat, 
  aes_string(x = 'UMAP1', y = 'UMAP2', colour = g3)) + 
  gg_tabula_rasa +
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
print_plot_eval(print((p3 + p4 + p5)/ (p1 + p2)),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('{g1}-{g2}-{g3}.pdf')))
```

```{r }
p_dat <- as.data.frame(M) %>%
  add_umap()

g1 = 'Galnt1'
g2 = 'Fgl2'
g3 = 'Cx3cl1'

g1 = 'Tnnt2'
g2 = 'Loxl3'
g2 = 'Bambi'
g2 = 'Batf2'
g2 = 'Cx3cl1'
g3 = 'Col12a1'
g3 = 'Galnt1'
p1 <- ggplot(p_dat, 
  aes_string(x = g1, y = g2, colour = g3)) + 
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p3 <- ggplot(p_dat, 
  aes_string(x = 'UMAP1', y = 'UMAP2', colour = g1)) + 
  gg_tabula_rasa +
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p4 <- ggplot(p_dat, 
  aes_string(x = 'UMAP1', y = 'UMAP2', colour = g2)) + 
  gg_tabula_rasa +
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
p2 <- ggplot(p_dat, 
  aes_string(x = 'UMAP1', y = 'UMAP2', colour = g3)) + 
  gg_tabula_rasa +
  geom_point(alpha = .3, size = .5) +
  scale_colour_viridis_c()
print_plot_eval(print((p3 + p4 + p2)/ p1),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('orig_{g1}-{g2}-{g3}.pdf')))
```

```{r }
```

```{r }
for (gs in names(gene_sets)) {
  print(exp_dynamics_panel(
    features = gene_sets[[gs]],
    merge_cn = 'sample_name',
    meta_data = sample_annotation,
    lookup_data = M_cpm,
    y_scale = 'linear',
    version = glue('220915_murine_limma_MRs_{gs}'),
    redo = F,
    leave_out_sn = F)
  )
}

  print(exp_dynamics_panel(
    features = 'Cxcl10',
    merge_cn = 'sample_name',
    meta_data = sample_annotation,
    lookup_data = M_cpm,
    y_scale = 'linear',
    version = glue('220915_murine_Cxcl10'),
    redo = F,
    leave_out_sn = F)
  )
```

```{r, warning=FALSE}
so_score <- ComputeGeneSetScores(
  so = so,
  assay = 'SCT',
  datatype = 'counts',
  weighting_funcs = all_weighting_funcs['unweighted'],
  genesets = gene_sets,
  # tV = apply(tM_human, 1, max),
  simplify_names = F
)

table(so_score@meta.data[, c('mouse', 'stim_group')]) > 0

p_dat <- assay2dtf(so_score, 
  s_vars = c('condition_name', 'sample_origin', 'ifn_conc',
    'sn_dilution', 'percent.mt', 'tnf_conc', 'duration', 'mouse'),
  assay = 'GS')  %>%
  dplyr::mutate(mouse = as.integer(stringr::str_replace(mouse,
        '6743_', ''))) %>%
  dplyr::group_by(stim_group) %>%
  dplyr::mutate(mouse = mouse - min(mouse) + 1) %>%
  # dplyr::mutate(mouse = glue::glue('{stim_group} - {mouse}')) %>%
  { . }

table(p_dat$mouse)
colnames(p_dat) <- stringr::str_replace(colnames(p_dat),
  '.vanilla.unweighted.sum', '')
```

```{r }
# p4 <- ggplot(p_dat, aes(x = log2(IFNy + 1), y = log2(TGFb + 1))) + 
p4 <- ggplot(p_dat, aes(x = IFNy, y = TGFb)) + 
  geom_point(alpha = .1) + 
  # geom_density_2d(alpha = .9) + 
  geom_density_2d_filled(contour_var = "ndensity") +
  geom_vline(xintercept = 100, color = 'indianred3', alpha = .4) +
  geom_hline(yintercept = 100, color = 'indianred3', alpha = .4) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  # stat_density() + 
  facet_grid(stim_group ~mouse)
print_plot_eval(print(p4),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('IFNy_vs_TGFb_per_mouse.pdf')))
```

```{r }
reticulate::use_condaenv('magic', required=TRUE)
pacman::p_load('Rmagic')
so_t <- so[, so@meta.data$stim_group == 'Mix + T']
so_t <- FindVariableFeatures(so_t)

# so_t <- magic(
#   so_t, 
#   assay = 'SCT', 
#   genes = unique(unname(unlist(gene_sets)))
# )
# exp(so_t@assays$SCT[,])
M <- as.matrix(exp(so_t@assays$SCT[VariableFeatures(so_t),])) %>%
  # subset_feats(unique(unname(unlist(gene_sets))))
  t() %>%
  { . }
M <- 1e6 * M / rowSums(M)
M <- sqrt(M)

readr::write_csv(as.data.frame(M), file.path(data_dir, '6743_Mix_T.csv'))
# bmmsc_MAGIC <- magic(M, genes=c('Mpo', 'Klf1', 'Ifitm1'))
```

```{r, eval=F, warning=FALSE}
# magic <- reticulate::import("magic")
# magic$check_pymagic_version()
# Rmagic::pymagic_is_available()
# Rmagic::magic(M)
pacman::p_load('Rmagic')
data(magic_testdata)
MAGIC_data <- magic(magic_testdata, genes=c("VIM", "CDH1", "ZEB1"))
```

```{r, warning=FALSE}
p0 <- ggplot(p_dat, aes(y = IFNy, x = stim_group)) + 
  geom_violin(draw_quantiles = c(.25, .5, .75)) 
p1 <- ggplot(p_dat, aes(y = TNFa, x = stim_group)) + 
  geom_violin(draw_quantiles = c(.25, .5, .75)) 
p2 <- ggplot(p_dat, aes(y = TGFb, x = stim_group)) + 
  geom_violin(draw_quantiles = c(.25, .5, .75)) 
p3 <- ggplot(p_dat, aes(x = log2(IFNy + 1), y = log2(TGFb + 1))) + 
  geom_point(alpha = .1) + 
  # stat_density() + 
  facet_grid(~stim_group)
print_plot_eval(print(p0 + p1 + p2 + p3),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('IFNy_vs_TGFb.pdf')))
```

```{r }
p_dat <- 
  colData(Nhood_expression) %>%
  as.data.frame() %>%
  tibble::rownames_to_column('cell_id')

p_dat <- inner_join(
  p_dat, 
  t(ComputeGeneSetScores(
    M = as.matrix(assay(Nhood_expression, 'logcounts')), 
    # M = nhoodExpression(Nhood_expression), 
    genesets = gene_sets,
    weighting_funcs = all_weighting_funcs[c('unweighted')]
  )) %>%
  as.data.frame() %>%
  tibble::rownames_to_column('cell_id')
)
```

```{r }
Nhood_expression <- calcNhoodExpression(sce)

p_dat <- 
  ComputeGeneSetScores(
    # M = as.matrix(assay(Nhood_expression, 'logcounts')), 
    M = nhoodExpression(Nhood_expression), 
    genesets = gene_sets,
    weighting_funcs = all_weighting_funcs[c('unweighted')]
  ) %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column('Nhood') %>%
  dplyr::mutate(Nhood = as.numeric(Nhood)) %>%
  dplyr::inner_join(all_NH_test_DA[[2]]) %>%
  # dplyr::mutate(IFNy, case_when(
  #     SpatialFDR > .25 ~ 0, 
  #     TRUE ~ IFNy))
  { . }
p1 <- 
  ggplot(p_dat, aes(x = IFNy, y = TGFb, colour = logFC, 
    size = -log10(SpatialFDR))) + 
  geom_point(alpha = .5) + 
  scale_colour_viridis_c() +
  theme()

print_plot_eval(print(p1),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('Nhood_IFNy_vs_TGFb.pdf')))
```

```{r }
# sce_s <- sce[, colData(sce)$stim_group == 'Mix + T']
# Nhood_expression <- calcNhoodExpression(sce_s)
p_dat <- 
  ComputeGeneSetScores(
    # M = as.matrix(assay(Nhood_expression, 'logcounts')), 
    M = nhoodExpression(Nhood_expression), 
    genesets = gene_sets,
    weighting_funcs = all_weighting_funcs[c('unweighted')]
  ) %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column('Nhood') %>%
  dplyr::mutate(Nhood = as.numeric(Nhood)) %>%
  dplyr::inner_join(all_NH_test_DA[[2]]) %>%
  # dplyr::mutate(IFNy, case_when(
  #     SpatialFDR > .25 ~ 0, 
  #     TRUE ~ IFNy))
  dplyr::filter(logFC > 0) %>%
  { . }
p1 <- 
  ggplot(p_dat, aes(x = IFNy, y = TGFb, colour = logFC, 
    size = -log10(SpatialFDR))) + 
  geom_point(alpha = .5) + 
  scale_colour_viridis_c() +
  theme()

print_plot_eval(print(p1),
  width = 12, height = 10,
  filename = file.path(out_dir,
    glue::glue('Nhood_IFNy_vs_TGFb_subs.pdf')))
```
