---
title: "Fig 3"
author: "Maarten Slagter"
---

```{r, warning=FALSE}
options('plot_force_file' = TRUE)
 
source('~/MirjamHoekstra/R/init.R')
tab <- targets_env$gs_param_table
out_dir <- file.path(Sys.getenv('img_dir'), 'fig3')
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
```

Mean expression heatmaps, not shown in manuscript

```{r }
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')

for (idx in c(8, 10, 12)) {
  load_prereqs(param_grid = tab, idx = idx)
  report_cp <- get_obj('report_cp')
  o_fn <- file.path(out_dir,
      glue::glue('expression_heatmaps-{report_cp}.pdf'))
  mean_expression_heatmaps(get_obj('GS_p_dat'), o_fn = o_fn)
}
```

# Panel B

UMAPs also for other experiments than experiment 6493, the one shown in panel B

```{r }
source(file.path(r_dir, 'get_knit_params.R'))

for (idx in c(8, 10, 12)) {
# for (idx in c(12)) {
# for (idx in c(8)) {
  # idx = 10
  # idx = 12
  load_prereqs(param_grid = tab, idx = idx)
  experiment <- get_obj('experiment')

  source(file.path(r_dir, 'GS_time_inference.R'))
  eval(time_inference_preproc)
  out_dir <- file.path(Sys.getenv('img_dir'), 'fig4', report_cp)
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

  if (interactive() && !test_rendering())
    source('~/MirjamHoekstra/R/init.R')
  p1 <- DimPlot(
    so,
    # group.by = group_var_cn_mode[[cn_mode]],
    group.by = 'stim_group',
    label.size = 2,
    # pt.size = 16, 
    pt.size = 1, 
    label = FALSE,
    # raster.dpi = c(512, 512).
    raster.dpi = 4 * c(512, 512),
    split.by = group_vars[length(group_vars)],
    # split.by = 'stim_group',
    raster = experiment != '6493') +
    # scale_colour_stim_group(so@meta.data) +
    theme_cyto_inf() +
    ggtitle('') +
    guides(color = guide_legend(ncol = 2))
  if (T && !experiment %in% c('6369', '6489')) {
    # p1 <- p1 + scale_colour_stim_group(so@meta.data, UMAP_mode = TRUE)
    p1 <- p1 + scale_colour_viridis_d()
  } else {
    p1 <- p1 + scale_colour_viridis_d(begin = .1, end = .8)
  }
  print_plot_eval(
    plot(p1),
    width = length(unique(so@meta.data$duration)) * 17.4 / 3,
    height = 10,
    filename = file.path(out_dir,
      glue::glue('exp{report_cp}_UMAP.pdf'))
  )
}
```

# Panel C

```{r }
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
source(file.path(r_dir, 'get_knit_params.R'))
idx = 12 #6493 in vivo
tab <- targets_env$gs_param_table
load_prereqs(param_grid = tab, idx = idx)
experiment <- get_obj('experiment')

GS_p_dat <- get_obj('GS_p_dat') %>%
  order_condition_name() %>%
  format_gs_names() %>%
  dplyr::filter(Ag == 'Ag-') %>%
  dplyr::mutate(condition_name = droplevels(condition_name))
```

```{r, warning=FALSE}
for (fn in c('IFNy', 'TNFa', 'synergy', 'IFNy.late', 'IFNy.plateau',
    'TNFa.early')) {
  for (plot_lgd in c(T, F)) {
    mk_ann_GS_vln(
      p_dat = GS_p_dat,
      cn_mode = 'all',
      fn = fn,
      fn_add = '6493_in_vivo',
      out_dir = out_dir,
      experiment = experiment,
      return_mode = 'file',
      p_values = 'all',
      plot_lgd = plot_lgd
    )
  }
}
```

```{r }
compute_all_pairwise_medians(GS_p_dat) %>%
  write_tsv(file.path(out_dir, 'pairwise_gs_comp_stats_6493_in_vivo.tsv'))
```

# Cell death proxies vs. gene set scores

Not in paper

```{r }
so <- get_obj('unfiltered_so') %>%
  ComputeGeneSetScores(
    weighting_funcs = all_weighting_funcs[c('unweighted')]
  )
cns = c('condition_name', 'duration', 'percent.ribo', 'percent.mt',
  'nCount_RNA')
p_dat <- create_GS_p_dat(so = so, meta_vars = cns)
```

```{r, warning=FALSE}
  of = file.path(out_dir, 'exp6601_gs_vs_cell_death.pdf')
  plots <-
    tidyr::expand_grid(
      x_var = c('TNFa', 'IFNy'),
      y_var = setdiff(cns, c('condition_name', 'duration'))
    ) %>%
    pmap(function(x_var, y_var) {
      p <- 
        p_dat %>%
        ggplot(aes_string(x = x_var, y = y_var, colour = 'synergy')) +
        ggrastr::rasterise(geom_point(), dpi = 300) + 
        facet_wrap('condition_name') +
        theme()
      return(p)
    })

    NC = 1; NR = 2
  # p1 <- wrap_plots(plots, guides = 'collect', ncol = NC, nrow = NR)
  # print_plot_eval(
  #   { print(p1) },
  #   width = 17.4, height = 25,
  #   filename = of)
  plot_panel_layout(
    plots = plots,
    labels = NULL,
    ncol = NC, nrow = NR, 
    filename = of
  )

```

```{r, eval=F}
p <- ggplot(GS_p_dat, 
  aes(x = TNFa, y = IFNy, colour = synergy)) + 
  geom_point() + 
  facet_wrap(~condition_name)
print_plot_eval(print(p),
  width = 17.4, height = 10,
  filename = file.path(out_dir,
    glue::glue('TNFa_pockets.pdf')))
```

# Panel B

```{r }
source(file.path(r_dir, 'get_knit_params.R'))

# idx = 12 (experiment 6493 in vivo) pertains to panel B
for (idx in c(8, 10, 12)) {
  load_prereqs(param_grid = tab, idx = idx)
  experiment <- get_obj('experiment')

  source(file.path(r_dir, 'GS_time_inference.R'))
  eval(time_inference_preproc)
  out_dir <- file.path(Sys.getenv('img_dir'), 'fig4', report_cp)
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

  if (interactive() && !test_rendering())
    source('~/MirjamHoekstra/R/init.R')
  p1 <- DimPlot(
    so,
    # group.by = group_var_cn_mode[[cn_mode]],
    group.by = 'stim_group',
    label.size = 2,
    # pt.size = 16, 
    pt.size = 1, 
    label = FALSE,
    # raster.dpi = c(512, 512).
    raster.dpi = 4 * c(512, 512),
    split.by = group_vars[length(group_vars)],
    # split.by = 'stim_group',
    raster = experiment != '6493') +
    # scale_colour_stim_group(so@meta.data) +
    theme_cyto_inf() +
    ggtitle('') +
    guides(color = guide_legend(ncol = 2))
  if (T && !experiment %in% c('6369', '6489')) {
    # p1 <- p1 + scale_colour_stim_group(so@meta.data, UMAP_mode = TRUE)
    p1 <- p1 + scale_colour_viridis_d()
  } else {
    p1 <- p1 + scale_colour_viridis_d(begin = .1, end = .8)
  }
  print_plot_eval(
    plot(p1),
    width = length(unique(so@meta.data$duration)) * 17.4 / 3,
    height = 10,
    filename = file.path(out_dir,
      glue::glue('exp{report_cp}_UMAP.pdf'))
  )
}
```


# Panel C

```{r }
if (interactive() && !test_rendering())
  source('~/MirjamHoekstra/R/init.R')
source(file.path(r_dir, 'get_knit_params.R'))
idx = 12 #6493 in vivo
tab <- targets_env$gs_param_table
load_prereqs(param_grid = tab, idx = idx)
experiment <- get_obj('experiment')

GS_p_dat <- get_obj('GS_p_dat') %>%
  order_condition_name() %>%
  format_gs_names() %>%
  dplyr::filter(Ag == 'Ag-') %>%
  dplyr::mutate(condition_name = droplevels(condition_name))
```

```{r, warning=FALSE}
for (fn in c('IFNy', 'TNFa', 'synergy', 'IFNy.late', 'IFNy.plateau',
    'TNFa.early')) {
  for (plot_lgd in c(T, F)) {
    mk_ann_GS_vln(
      p_dat = GS_p_dat,
      cn_mode = 'all',
      fn = fn,
      fn_add = '6493_in_vivo',
      out_dir = out_dir,
      experiment = experiment,
      return_mode = 'file',
      p_values = 'all',
      plot_lgd = plot_lgd
    )
  }
}
```

```{r }
compute_all_pairwise_medians(GS_p_dat) %>%
  write_tsv(file.path(out_dir, 'pairwise_gs_comp_stats_6493_in_vivo.tsv'))
```


