suppressWarnings(suppressMessages(suppressPackageStartupMessages({
  pacman::p_load(pkgs, character.only = TRUE)

  source(file.path(Sys.getenv('r_dir'), 'helpers.R'))
  source(file.path(Sys.getenv('r_dir'), 'targets_init.R'))
  source(file.path('targets', '1-param_grid.R'))
  source(file.path(Sys.getenv('r_dir'), 'S3.R'))
  source(file.path(Sys.getenv('r_dir'), 'format_stim_group.R'))
  source(file.path(Sys.getenv('r_dir'), 'assess_clusters.R'))
  source(file.path(Sys.getenv('r_dir'), 'genesets.R'))
  source(file.path(Sys.getenv('r_dir'), 'RunTMM.R'))
  source(file.path(Sys.getenv('r_dir'), 'experiment_meta_data.R'))
  source(file.path(Sys.getenv('r_dir'), 'explore_clusters.R'))
  source(file.path(Sys.getenv('r_dir'), 'plotting.R'))
  source(file.path(Sys.getenv('r_dir'), 'data_integration.R'))
  source(file.path(Sys.getenv('r_dir'), 'preprocessing_sc.R'))
  source(file.path(Sys.getenv('r_dir'), 'time_informativeness.R'))
  source(file.path(Sys.getenv('r_dir'), 'limma.R'))
  source(file.path(Sys.getenv('r_dir'), 'mouse.R'))
  source(file.path(Sys.getenv('r_dir'), 'select_genes.R'))
  source(file.path(Sys.getenv('r_dir'), 'geneset_scores.R'))
  source(file.path(Sys.getenv('r_dir'), 'geneset_plots.R'))
  source(file.path(Sys.getenv('r_dir'), 'AUC_comp_gs.R'))
})))

Sys.setenv(HDF5_USE_FILE_LOCKING='FALSE')
# Sys.getenv('HDF5_USE_FILE_LOCKING')
